name: tetset

on:
  push:
    branches: none # [ main ]
  pull_request:
    branches: none # [ main ]
    
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build-dotnet-app:

    runs-on: ubuntu-latest

    steps:
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 4.6.x
