name: 030-dotnet-workflow

on:
  push:
    branches: none # [ main ]
  pull_request:
    branches: none # [ main ]
    
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build-dotnet-app:

    runs-on: ubuntu-latest
    
    defaults:
      run:
        working-directory: 03-app-dotnet

    steps:
    - uses: actions/checkout@v3
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.17
